"""Render the evaluation results as a Markdown report."""

from collections import Counter

from matching.config import MATCH_THRESHOLD, REVIEW_THRESHOLD


def fmt(m: dict) -> str:
    return f"{m['precision']:.2f} | {m['recall']:.2f} | {m['f1']:.2f} | {m['tp']} | {m['fp']} | {m['fn']}"


def table(header: list[str], rows: list[list]) -> list[str]:
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    lines += ["| " + " | ".join(str(cell) for cell in row) + " |" for row in rows]
    return lines


def render(ev: dict) -> str:
    labels = ev["labels"]
    lines = [
        "# Evaluation report",
        "",
        "Generated by `python run_pipeline.py`. All numbers below come from that run.",
        "",
        f"- Explicit labels: {len(labels.explicit)} pairs "
        f"({sum(labels.explicit.values())} matches, {len(labels.explicit) - sum(labels.explicit.values())} non-matches)",
        f"- Implied negatives: {len(labels.implied)} pairs (derived; see README)",
        f"- Thresholds: match >= {MATCH_THRESHOLD}, review >= {REVIEW_THRESHOLD}",
        "",
        "## 1. Headline metrics",
        "",
        "Metrics only cover labeled pairs. A predicted match without a label is neither right nor wrong here.",
        "",
    ]
    rows = []
    for name, key in [("Naive baseline (same date + client attending)", "baseline"),
                      ("Rules matcher (submitted)", "rules")]:
        rows.append([name, "explicit", fmt(ev[key]["explicit"])])
        rows.append([name, "explicit + implied", fmt(ev[key]["combined"])])
    ml = ev["ml"]
    rows.append(["Logistic regression, leave-one-pair-out", "explicit", fmt(ml["explicit_loo"])])
    rows.append(["Logistic regression, leave-one-CRM-record-out", "explicit + implied", fmt(ml["combined_grouped"])])
    lines += table(["Method", "Labels", "Precision", "Recall", "F1", "TP", "FP", "FN"], rows)

    lines += ["", "Baseline errors (explicit + implied):", ""]
    lines += [f"- {kind}: {pairs or 'none'}" for kind, pairs in ev["baseline_errors"].items()]
    lines += ["", "Rules matcher errors (explicit + implied):", ""]
    lines += [f"- {kind}: {pairs or 'none'}" for kind, pairs in ev["rules_errors"].items()]

    lines += ["", "## 2. Score margins on labeled pairs (date blocking skipped)", "",
              "Every labeled non-match falls on a different date, so blocking alone rejects it. "
              "Scoring the labeled pairs directly shows whether the score also separates them.", ""]
    lines += table(["CRM", "Calendar", "Label", "Confidence"],
                   [[*row["pair"], "match" if row["label"] else "non-match", row["confidence"]]
                    for row in ev["margins"]])
    positives = [row["confidence"] for row in ev["margins"] if row["label"]]
    negatives = [row["confidence"] for row in ev["margins"] if not row["label"]]
    lines += ["", f"Lowest labeled match: **{min(positives)}**. Highest labeled non-match: **{max(negatives)}**."]

    lines += ["", "## 3. Threshold sweep (rules matcher)", ""]
    lines += table(["Match threshold", "Predicted matches", "F1 explicit", "F1 explicit + implied"],
                   [[row["threshold"], row["predicted"], f"{row['explicit']['f1']:.2f}", f"{row['combined']['f1']:.2f}"]
                    for row in ev["sweep"]])

    lines += ["", "## 4. Ablation: remove one signal, re-run everything", ""]
    lines += table(["Signal removed", "F1 explicit", "F1 explicit + implied", "Predictions changed vs full model"],
                   [[row["removed"], f"{row['explicit']['f1']:.2f}", f"{row['combined']['f1']:.2f}",
                     row["changed"] or "none"] for row in ev["ablation"]])

    lines += ["", "## 5. Learned weights (logistic regression, fit on all labels)", "",
              "For comparison with the hand-set weights. Not used by the submitted matcher.", ""]
    lines += table(["Signal", "Hand-set weight", "LR coef (explicit)", "LR coef (explicit + implied)"],
                   [[name, ev["weights"][name], ml["weights_explicit"][name], ml["weights_combined"][name]]
                    for name in ev["weights"]])

    lines += ["", "## 6. Predictions not covered by any label (need manual review)", ""]
    lines += table(["CRM", "Calendar", "Confidence", "Decision", "Flags"],
                   [[p.crm_id, p.calendar_id, p.confidence, p.decision, "; ".join(p.flags) or "-"]
                    for p in ev["unlabeled"]])

    lines += ["", "## 7. Near misses: unassigned candidates scoring >= 0.4", ""]
    lines += table(["CRM", "Calendar", "Confidence", "Why it scored"],
                   [[p.crm_id, p.calendar_id, p.confidence,
                     ", ".join(f"{k}={v}" for k, v in p.signals.items() if v is not None)]
                    for p in ev["near_misses"]] or [["-", "-", "-", "none"]])

    dup = ev["duplicates"]
    lines += ["", "## 8. Calendar duplicate detection", "",
              f"- Labeled duplicates: {dup['labeled']}",
              f"- Predicted duplicates: {dup['predicted']}",
              f"- Labeled duplicates found: {len(dup['found'])}/{len(dup['labeled'])}"]

    issue_counts = Counter(issue.split(":")[0] for issues in ev["issues"].values() for issue in issues)
    lines += ["", "## 9. Data-quality issues found", ""]
    lines += table(["Issue", "Count"], [[issue, count] for issue, count in sorted(issue_counts.items())])
    lines += [""]
    lines += [f"- {record_id}: {'; '.join(issues)}" for record_id, issues in ev["issues"].items()]
    return "\n".join(lines) + "\n"
